Repository should-i-pay/should-i-pay, pull requests merged in 2020-08, with the labels that each got.

#2 Fix expo web dev build optionalChaining error
  babel.config.js
  package-lock.json
  package.json
  webpack.config.js
Labels: bug

#9 chore(npm): add: script for linting
  .eslintignore
  .github/workflows/main.yml
  .lintstagedrc
  .prettierignore
  package.json
Labels: enhancement

#1 Add logo and readme
  README.md
  assets/images/cover.png
  package-lock.json
  package.json
Labels: documentation
